---


- name: Add the user
  user:
    name: mynameismud
    shell: /bin/bash
    groups: sudo
    append: yes

- name: Set authorized key taken from file
  authorized_key:
    user: mynameismud
    state: present
    key: "{{ lookup('file', '/home/mynameismud/.ssh/id_ed25519.pub') }}"

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'